package tn.dhc.controllers;

import javafx.animation.PauseTransition;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.*;
import javafx.stage.Stage;
import tn.dhc.entities.Event;
import tn.dhc.services.CohereEventDescriptionService;
import tn.dhc.services.EventService;

import java.io.IOException;
import java.time.LocalDate;
import java.time.LocalTime;
import javafx.util.Duration;

public class AjouterEvent {
    private static final int MAX_EVENT_DESCRIPTION = 240;

    @FXML
    private DatePicker addEventDate;

    @FXML
    private ComboBox<String> addEventDebut;

    @FXML
    private ComboBox<String> addEventFin;

    @FXML
    private TextField addEventDescr;

    @FXML
    private TextField addEventTheme;

    @FXML
    private TextField addEventTitre;

    private final EventService eventService = new EventService();
    private final CohereEventDescriptionService cohereEventDescriptionService = new CohereEventDescriptionService();
    private final PauseTransition titleDebounce = new PauseTransition(Duration.millis(900));
    private String lastGeneratedTitle = "";

    @FXML
    public void initialize() {

        for (int h = 8; h <= 18; h++) {
            addEventDebut.getItems().add(String.format("%02d:00", h));
            addEventDebut.getItems().add(String.format("%02d:30", h));

            addEventFin.getItems().add(String.format("%02d:00", h));
            addEventFin.getItems().add(String.format("%02d:30", h));
        }

        addEventDebut.setValue("08:00");
        addEventFin.setValue("08:30");

        addEventTitre.textProperty().addListener((obs, oldValue, newValue) -> {
            titleDebounce.stop();
            String t = newValue == null ? "" : newValue.trim();
            if (t.length() < 4) {
                return;
            }
            titleDebounce.setOnFinished(e -> autoGenerateDescriptionFromTitle());
            titleDebounce.playFromStart();
        });
    }

    @FXML
    void ajouterEvent(ActionEvent event) {

        try {
            LocalDate date = addEventDate.getValue();
            String debutStr = addEventDebut.getValue();
            String finStr = addEventFin.getValue();

            String titre = addEventTitre.getText();
            String theme = addEventTheme.getText();
            String descr = addEventDescr.getText();
            if (descr != null && descr.length() > MAX_EVENT_DESCRIPTION) {
                descr = descr.substring(0, MAX_EVENT_DESCRIPTION).trim();
                addEventDescr.setText(descr);
            }

            if (date == null || debutStr == null || finStr == null ||
                    titre == null || titre.isEmpty() ||
                    theme == null || theme.isEmpty() ||
                    descr == null || descr.isEmpty()) {

                showAlert(Alert.AlertType.ERROR, "Erreur", "Veuillez remplir tous les champs !");
                return;
            }

            LocalTime debut = LocalTime.parse(debutStr);
            LocalTime fin = LocalTime.parse(finStr);

            if (!fin.isAfter(debut)) {
                showAlert(Alert.AlertType.ERROR, "Erreur", "Heure invalide !");
                return;
            }


            Event e = new Event(
                    0,
                    titre,
                    theme,
                    descr,
                    date,
                    debut,
                    fin,
                    null,
                    1,
                    1
            );

            eventService.ajouter(e); 

            showAlert(Alert.AlertType.INFORMATION, "Succès", "Event ajouté avec succès !");
            FXMLLoader loader = new FXMLLoader(getClass().getResource("/Dashboard.fxml"));
            Parent root = loader.load();

            Dashboard controller = loader.getController();

            Stage stage = (Stage) ((Node) event.getSource()).getScene().getWindow();
            stage.setScene(new Scene(root));

        } catch (Exception ex) {
            showAlert(Alert.AlertType.ERROR, "Erreur", ex.getMessage());
        }
    }

    @FXML
    public void annuler(ActionEvent event) throws IOException {
        addEventDate.setValue(null);
        addEventDebut.setValue("08:00");
        addEventFin.setValue("08:30");

        addEventTitre.clear();
        addEventTheme.clear();
        addEventDescr.clear();
        FXMLLoader loader = new FXMLLoader(getClass().getResource("/Dashboard.fxml"));
        Parent root = null;
        try {
            root = loader.load();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }

        Dashboard controller = loader.getController();

        Stage stage = (Stage) ((Node) event.getSource()).getScene().getWindow();
        stage.setScene(new Scene(root));
    }

    private void showAlert(Alert.AlertType type, String title, String message) {
        Alert alert = new Alert(type);
        alert.setTitle(title);
        alert.setHeaderText(null);
        alert.setContentText(message);
        alert.showAndWait();
    }

    private void autoGenerateDescriptionFromTitle() {
        if (addEventTitre == null || addEventDescr == null) {
            return;
        }
        String title = addEventTitre.getText() != null ? addEventTitre.getText().trim() : "";
        String currentDesc = addEventDescr.getText() != null ? addEventDescr.getText().trim() : "";
        if (title.isBlank()) {
            return;
        }
        if (!currentDesc.isBlank()) {
            return;
        }
        if (title.equalsIgnoreCase(lastGeneratedTitle)) {
            return;
        }

        addEventDescr.setPromptText("Generation automatique via Cohere...");
        javafx.concurrent.Task<String> task = new javafx.concurrent.Task<>() {
            @Override
            protected String call() throws Exception {
                return cohereEventDescriptionService.generateDescriptionFromTitle(title);
            }
        };
        task.setOnSucceeded(ev -> {
            String generated = task.getValue();
            if (generated != null && !generated.isBlank()) {
                String safe = generated.length() > MAX_EVENT_DESCRIPTION
                        ? generated.substring(0, MAX_EVENT_DESCRIPTION).trim()
                        : generated;
                addEventDescr.setText(safe);
                lastGeneratedTitle = title;
            }
            addEventDescr.setPromptText("Choisissez un titre");
        });
        task.setOnFailed(ev -> {
            addEventDescr.setText("Description automatique temporairement indisponible. Veuillez saisir une description manuellement.");
            addEventDescr.setPromptText("Choisissez un titre");
        });

        Thread worker = new Thread(task, "cohere-event-description");
        worker.setDaemon(true);
        worker.start();
    }
}